apiVersion: v1
kind: ConfigMap
metadata:
  name: ecoran-config
data:
  {{- $files := .Files }}
  {{- range tuple "config.yaml" "ecoran.py" }}
  {{ . }}: |-
{{ $files.Get . | trim | indent 4 }}
  {{- end }}
