apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: ecoran
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecoran
  template:
    metadata:
      labels:
        app: ecoran
    spec:
      containers:
        - name: ecoran
          image: "docker.io/boing7898/ecoran:latest"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /mnt/data  # Mount path inside the container
              name: storage
            - name: ecoran-config
              mountPath: /opt/ecoran/
              subPath: config.yaml
          stdin: true
          tty: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: local-pvc  # This should match your PVC name
        - name: ecoran-config
          configMap:
            name: ecoran-config
