apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: ecoran
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ecoran
  template:
    metadata:
      labels:
        app: ecoran
    spec:
      containers:
        - name: ecoran
          image: "docker.io/boing7898/ecoran:latest"
          imagePullPolicy: Always
          command: ["sleep"]
          args: ["infinity"]
          volumeMounts:
            - name: xapp-rtg
              mountPath: /opt/ric/config/uta-rtg.rt
              subPath: routes.rtg
            - name: script-lib
              mountPath: /opt/ecoran/lib/
            - name: script-asn1
              mountPath: /opt/ecoran/lib/asn1/
            - mountPath: /mnt/data
              name: storage
            - name: ecoran-config
              mountPath: /opt/ecoran/
          stdin: true
          tty: true
          securityContext:
            privileged: true
      volumes:
        - name: xapp-rtg
          configMap:
            name: xapp-rtg
        - name: script-lib
          configMap:
            name: xapp-lib
        - name: script-asn1
          configMap:
            name: xapp-asn1
        - name: storage
          persistentVolumeClaim:
            claimName: local-pvc
        - name: ecoran-config
          configMap:
            name: ecoran-config
